### ISSUE TITLE
works without TLS: NoTLS: true, and StartTLS: false

### ISSUE THREAD

**Issue by ikq** [mattn/go-xmpp#66]
IMHO here bug in switch, should be:

``` go
func (c *Client) startTLSIfRequired(f *streamFeatures, o *Options, domain string) (*streamFeatures, error) {

    switch {

    case f.StartTLS == nil:
        // the server does not support STARTTLS
        return f, nil
    case f.StartTLS.Required != nil: // the server requires STARTTLS.
    case o.StartTLS:
        break // the user wants STARTTLS and the server supports it.
    default:
        return f, nil
    }
.......
```

**Comment by mattn** [comment]
Could you please send me pull-request? also #67 #68

**Comment by ik-** [comment]
Thanks for response and library.
It can take some time, because before I should learn how to make forking project and pull request in github, and now I'm in small vacation...

I start "playing" with your library, to check if I can use it to communicate with our XMPP server 
(with no standard XMPP extensions).
And if found something that prevent me continue the testing - simply fix it in my local copy.

**Comment by mattn** [comment]
Closed by https://github.com/mattn/go-xmpp/pull/110
